INSERT INTO hesa_code_tables (id, field, code, description, created_at, updated_at) VALUES
('hc-eth-10','ETHNIC','10','White',NOW(),NOW()),
('hc-eth-15','ETHNIC','15','Gypsy or Traveller',NOW(),NOW()),
('hc-eth-21','ETHNIC','21','Black or Black British - Caribbean',NOW(),NOW()),
('hc-eth-22','ETHNIC','22','Black or Black British - African',NOW(),NOW()),
('hc-eth-31','ETHNIC','31','Asian or Asian British - Indian',NOW(),NOW()),
('hc-eth-32','ETHNIC','32','Asian or Asian British - Pakistani',NOW(),NOW()),
('hc-eth-33','ETHNIC','33','Asian or Asian British - Bangladeshi',NOW(),NOW()),
('hc-eth-34','ETHNIC','34','Chinese',NOW(),NOW()),
('hc-eth-39','ETHNIC','39','Other Asian background',NOW(),NOW()),
('hc-eth-41','ETHNIC','41','Mixed - White and Black Caribbean',NOW(),NOW()),
('hc-eth-42','ETHNIC','42','Mixed - White and Black African',NOW(),NOW()),
('hc-eth-43','ETHNIC','43','Mixed - White and Asian',NOW(),NOW()),
('hc-eth-50','ETHNIC','50','Arab',NOW(),NOW()),
('hc-eth-80','ETHNIC','80','Other ethnic background',NOW(),NOW()),
('hc-eth-90','ETHNIC','90','Not known',NOW(),NOW()),
('hc-eth-98','ETHNIC','98','Information refused',NOW(),NOW()),
('hc-dis-00','DISABLE','00','No known disability',NOW(),NOW()),
('hc-dis-02','DISABLE','02','Blind/partially sighted',NOW(),NOW()),
('hc-dis-03','DISABLE','03','Deaf/hard of hearing',NOW(),NOW()),
('hc-dis-04','DISABLE','04','Wheelchair user/mobility difficulty',NOW(),NOW()),
('hc-dis-06','DISABLE','06','Mental health condition',NOW(),NOW()),
('hc-dis-07','DISABLE','07','An unseen disability',NOW(),NOW()),
('hc-dis-08','DISABLE','08','Multiple disabilities',NOW(),NOW()),
('hc-dis-10','DISABLE','10','Autistic Spectrum Condition',NOW(),NOW()),
('hc-dis-11','DISABLE','11','Specific learning difficulty',NOW(),NOW()),
('hc-dis-53','DISABLE','53','Long standing illness',NOW(),NOW()),
('hc-dis-96','DISABLE','96','Other disability',NOW(),NOW()),
('hc-fun-1','FUNDCODE','1','OfS/HEFCW/SFC funded',NOW(),NOW()),
('hc-fun-2','FUNDCODE','2','Not OfS funded - UK fee',NOW(),NOW()),
('hc-fun-5','FUNDCODE','5','Not OfS funded - overseas fee',NOW(),NOW()),
('hc-fun-7','FUNDCODE','7','No fee',NOW(),NOW()),
('hc-msf-01','MSTUFEE','01','No award or financial backing',NOW(),NOW()),
('hc-msf-02','MSTUFEE','02','UK SLC',NOW(),NOW()),
('hc-msf-04','MSTUFEE','04','UK research council',NOW(),NOW()),
('hc-msf-09','MSTUFEE','09','UK industry/commerce',NOW(),NOW()),
('hc-msf-40','MSTUFEE','40','International - self-funded',NOW(),NOW()),
('hc-msf-50','MSTUFEE','50','International - overseas government',NOW(),NOW()),
('hc-fee-1','FEEELIG','1','Home - England',NOW(),NOW()),
('hc-fee-2','FEEELIG','2','Home - Scotland',NOW(),NOW()),
('hc-fee-3','FEEELIG','3','Home - Wales',NOW(),NOW()),
('hc-fee-4','FEEELIG','4','Home - Northern Ireland',NOW(),NOW()),
('hc-fee-5','FEEELIG','5','EU (transitional)',NOW(),NOW()),
('hc-fee-6','FEEELIG','6','Islands',NOW(),NOW()),
('hc-fee-9','FEEELIG','9','International',NOW(),NOW()),
('hc-mod-01','MODE','01','Full-time according to funding council',NOW(),NOW()),
('hc-mod-02','MODE','02','Other full-time',NOW(),NOW()),
('hc-mod-23','MODE','23','Part-time 0.5 FTE',NOW(),NOW()),
('hc-mod-24','MODE','24','Part-time 0.5 to 1.0 FTE',NOW(),NOW()),
('hc-mod-25','MODE','25','Part-time less than 0.5 FTE',NOW(),NOW()),
('hc-tyr-1','TYPEYR','1','Standard year',NOW(),NOW()),
('hc-tyr-2','TYPEYR','2','Sandwich year out',NOW(),NOW()),
('hc-tyr-6','TYPEYR','6','Study abroad year',NOW(),NOW()),
('hc-tyr-7','TYPEYR','7','Intercalated year',NOW(),NOW()),
('hc-rsn-01','RSNEND','01','Qualification obtained',NOW(),NOW()),
('hc-rsn-02','RSNEND','02','Transferred to another provider',NOW(),NOW()),
('hc-rsn-03','RSNEND','03','Health reasons',NOW(),NOW()),
('hc-rsn-05','RSNEND','05','Financial reasons',NOW(),NOW()),
('hc-rsn-06','RSNEND','06','Other personal reasons',NOW(),NOW()),
('hc-rsn-07','RSNEND','07','Written off after lapse of time',NOW(),NOW()),
('hc-rsn-08','RSNEND','08','Exclusion',NOW(),NOW()),
('hc-rsn-09','RSNEND','09','Academic failure',NOW(),NOW()),
('hc-rel-01','RELIGION','01','No religion',NOW(),NOW()),
('hc-rel-02','RELIGION','02','Christian',NOW(),NOW()),
('hc-rel-03','RELIGION','03','Buddhist',NOW(),NOW()),
('hc-rel-04','RELIGION','04','Hindu',NOW(),NOW()),
('hc-rel-05','RELIGION','05','Jewish',NOW(),NOW()),
('hc-rel-06','RELIGION','06','Muslim',NOW(),NOW()),
('hc-rel-07','RELIGION','07','Sikh',NOW(),NOW()),
('hc-rel-08','RELIGION','08','Spiritual',NOW(),NOW()),
('hc-rel-98','RELIGION','98','Information refused',NOW(),NOW()),
('hc-sex-1','SEXORT','1','Heterosexual',NOW(),NOW()),
('hc-sex-2','SEXORT','2','Gay man',NOW(),NOW()),
('hc-sex-3','SEXORT','3','Gay woman/lesbian',NOW(),NOW()),
('hc-sex-4','SEXORT','4','Bisexual',NOW(),NOW()),
('hc-sex-5','SEXORT','5','Other',NOW(),NOW()),
('hc-sex-98','SEXORT','98','Information refused',NOW(),NOW())
ON CONFLICT (field, code) DO NOTHING;
