import { Router } from 'express';
import { authenticateJWT } from '../middleware/auth';

import { studentsRouter } from './students/students.router';
import { personsRouter } from './persons/persons.router';
import { demographicsRouter } from './demographics/demographics.router';
import { identifiersRouter } from './identifiers/identifiers.router';
import { facultiesRouter } from './faculties/faculties.router';
import { schoolsRouter } from './schools/schools.router';
import { departmentsRouter } from './departments/departments.router';
import { programmesRouter } from './programmes/programmes.router';
import { modulesRouter } from './modules/modules.router';
import { programmeModulesRouter } from './programme-modules/programme-modules.router';
import { programmeApprovalsRouter } from './programme-approvals/programme-approvals.router';
import { applicationsRouter } from './applications/applications.router';
import { qualificationsRouter } from './qualifications/qualifications.router';
import { referencesRouter } from './references/references.router';
import { offersRouter } from './offers/offers.router';
import { interviewsRouter } from './interviews/interviews.router';
import { clearanceChecksRouter } from './clearance-checks/clearance-checks.router';
import { admissionsEventsRouter } from './admissions-events/admissions-events.router';
import { enrolmentsRouter } from './enrolments/enrolments.router';
import { moduleRegistrationsRouter } from './module-registrations/module-registrations.router';
import { programmeRoutesRouter } from './programme-routes/programme-routes.router';
import { assessmentsRouter } from './assessments/assessments.router';
import { marksRouter } from './marks/marks.router';
import { secondMarkingRouter } from './second-marking/second-marking.router';
import { anonymousMarkingRouter } from './anonymous-marking/anonymous-marking.router';
import { submissionsRouter } from './submissions/submissions.router';
import { moduleResultsRouter } from './module-results/module-results.router';
import { examBoardsRouter } from './exam-boards/exam-boards.router';
import { progressionsRouter } from './progressions/progressions.router';
import { awardsRouter } from './awards/awards.router';
import { transcriptsRouter } from './transcripts/transcripts.router';
import { financeRouter } from './finance/finance.router';
import { feeAssessmentsRouter } from './fee-assessments/fee-assessments.router';
import { invoicesRouter } from './invoices/invoices.router';
import { paymentsRouter } from './payments/payments.router';
import { paymentPlansRouter } from './payment-plans/payment-plans.router';
import { paymentInstalmentsRouter } from './payment-instalments/payment-instalments.router';
import { sponsorAgreementsRouter } from './sponsor-agreements/sponsor-agreements.router';
import { sponsorsRouter } from './sponsors/sponsors.router';
import { sponsorInvoicesRouter } from './sponsor-invoices/sponsor-invoices.router';
import { bursaryFundsRouter } from './bursary-funds/bursary-funds.router';
import { bursaryApplicationsRouter } from './bursary-applications/bursary-applications.router';
import { creditNotesRouter } from './credit-notes/credit-notes.router';
import { refundApprovalsRouter } from './refund-approvals/refund-approvals.router';
import { attendanceRouter } from './attendance/attendance.router';
import { supportRouter } from './support/support.router';
import { ukviRouter } from './ukvi/ukvi.router';
import { ecClaimsRouter } from './ec-claims/ec-claims.router';
import { appealsRouter } from './appeals/appeals.router';
import { documentsRouter } from './documents/documents.router';
import { communicationsRouter } from './communications/communications.router';
import { auditRouter } from './audit/audit.router';
import { reportsRouter } from './reports/reports.router';
import { webhooksRouter } from './webhooks/webhooks.router';
import { configRouter } from './config/config.router';
import { hesaRouter } from './hesa/hesa.router';
import { accommodationRouter } from './accommodation/accommodation.router';
import { governanceRouter } from './governance/governance.router';

import identityGroup from './identity/group-index';
import admissionsGroup from './admissions/group-index';
import enrolmentGroup from './enrolment/group-index';
import curriculumGroup from './curriculum/group-index';
import assessmentGroup from './assessment/group-index';
import progressionGroup from './progression/group-index';
import studentSupportGroup from './student-support/group-index';
import complianceGroup from './compliance/group-index';
import platformGroup from './platform/group-index';

import identityGroupRouter from './identity/group-index';
import admissionsGroupRouter from './admissions/group-index';
import enrolmentGroupRouter from './enrolment/group-index';
import curriculumGroupRouter from './curriculum/group-index';
import assessmentGroupRouter from './assessment/group-index';
import progressionGroupRouter from './progression/group-index';
import studentSupportGroupRouter from './student-support/group-index';
import complianceGroupRouter from './compliance/group-index';
import platformGroupRouter from './platform/group-index';

export const apiV1Router = Router();
apiV1Router.use(authenticateJWT);

apiV1Router.use('/students', studentsRouter);
apiV1Router.use('/persons', personsRouter);
apiV1Router.use('/demographics', demographicsRouter);
apiV1Router.use('/identifiers', identifiersRouter);
apiV1Router.use('/faculties', facultiesRouter);
apiV1Router.use('/schools', schoolsRouter);
apiV1Router.use('/departments', departmentsRouter);
apiV1Router.use('/programmes', programmesRouter);
apiV1Router.use('/modules', modulesRouter);
apiV1Router.use('/programme-modules', programmeModulesRouter);
apiV1Router.use('/programme-approvals', programmeApprovalsRouter);
apiV1Router.use('/applications', applicationsRouter);
apiV1Router.use('/qualifications', qualificationsRouter);
apiV1Router.use('/references', referencesRouter);
apiV1Router.use('/offers', offersRouter);
apiV1Router.use('/interviews', interviewsRouter);
apiV1Router.use('/clearance-checks', clearanceChecksRouter);
apiV1Router.use('/admissions-events', admissionsEventsRouter);
apiV1Router.use('/enrolments', enrolmentsRouter);
apiV1Router.use('/module-registrations', moduleRegistrationsRouter);
apiV1Router.use('/programme-routes', programmeRoutesRouter);
apiV1Router.use('/assessments', assessmentsRouter);
apiV1Router.use('/marks', marksRouter);
apiV1Router.use('/second-marking', secondMarkingRouter);
apiV1Router.use('/anonymous-marking', anonymousMarkingRouter);
apiV1Router.use('/submissions', submissionsRouter);
apiV1Router.use('/module-results', moduleResultsRouter);
apiV1Router.use('/exam-boards', examBoardsRouter);
apiV1Router.use('/progressions', progressionsRouter);
apiV1Router.use('/awards', awardsRouter);
apiV1Router.use('/transcripts', transcriptsRouter);
apiV1Router.use('/finance', financeRouter);
apiV1Router.use('/fee-assessments', feeAssessmentsRouter);
apiV1Router.use('/invoices', invoicesRouter);
apiV1Router.use('/payments', paymentsRouter);
apiV1Router.use('/payment-plans', paymentPlansRouter);
apiV1Router.use('/payment-instalments', paymentInstalmentsRouter);
apiV1Router.use('/sponsor-agreements', sponsorAgreementsRouter);
apiV1Router.use('/sponsors', sponsorsRouter);
apiV1Router.use('/sponsor-invoices', sponsorInvoicesRouter);
apiV1Router.use('/bursary-funds', bursaryFundsRouter);
apiV1Router.use('/bursary-applications', bursaryApplicationsRouter);
apiV1Router.use('/credit-notes', creditNotesRouter);
apiV1Router.use('/refund-approvals', refundApprovalsRouter);
apiV1Router.use('/attendance', attendanceRouter);
apiV1Router.use('/support', supportRouter);
apiV1Router.use('/ukvi', ukviRouter);
apiV1Router.use('/ec-claims', ecClaimsRouter);
apiV1Router.use('/appeals', appealsRouter);
apiV1Router.use('/documents', documentsRouter);
apiV1Router.use('/communications', communicationsRouter);
apiV1Router.use('/audit', auditRouter);
apiV1Router.use('/reports', reportsRouter);
apiV1Router.use('/webhooks', webhooksRouter);
apiV1Router.use('/config', configRouter);
apiV1Router.use('/hesa', hesaRouter);
apiV1Router.use('/accommodation', accommodationRouter);
apiV1Router.use('/governance', governanceRouter);

// ── Domain Group Mounts (Phase 12a — additive, flat routes preserved above) ──
apiV1Router.use('/identity', identityGroup);
apiV1Router.use('/admissions', admissionsGroup);
apiV1Router.use('/enrolment', enrolmentGroup);
apiV1Router.use('/curriculum', curriculumGroup);
apiV1Router.use('/assessment', assessmentGroup);
apiV1Router.use('/progression', progressionGroup);
apiV1Router.use('/student-support', studentSupportGroup);
apiV1Router.use('/compliance', complianceGroup);
apiV1Router.use('/platform', platformGroup);
